env:
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {

'max-len': ["error", { "code": 200 }],
  "import/extensions": [
      "error",
      "ignorePackages",
    {
      "js": "always"
    }
  ]
}
